### ISSUE TITLE
Ревью

### ISSUE THREAD

**Issue by mityaginkontur** [MMIshark/SeleniumTestForPractice_Makarova#1]
95 строка

```
public void Authorization()
```

Метод с Авторизацией. Ты не дожидаешься конца авторизации где браузер тебя редиректит на /news и нет ожидания. Следовательно будут нестабильные тесты где сразу после авторизации в SetUp ты попробуешь перейти на другую страницу через driver.Navigate()

120 строка

```
communitiesTitle.Should().NotBeNull();
```

Мы не используем проверки в методах. Проверки должны быть в самих тестах и как правило в самом конце Arrange-Act-Assert паттерн.

---

Собственно из предыдущего выливаются следующие проблемы

Тест

```
public void OpenCommunitiesOnBigScreen()
```

Не имеет проверки в самом методе с тестом в конце (проверка должна быть в методе с тестом, а не в методе который в тесте вызывается)

Тест 

```
public void OpenCommunitiesOnSmallScreen()
```

Не имеет проверки в самом методе с тестом (проверка должна быть в методе с тестом, а не в методе который в тесте вызывается)

**Comment by MMIshark** [comment]
Исправлено
